name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        swift-version:
          - 6.0.3
          - 6.1.0

    runs-on: macos-latest
    name: Test (Swift ${{ matrix.swift-version }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift on macOS
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
